"""add session tracking fields

Revision ID: 0ff2b0c50fa7
Revises: init
Create Date: 2026-06-21 00:47:55.563572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0ff2b0c50fa7'
down_revision: Union[str, Sequence[str], None] = 'init'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_user', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_nullable=False)
    op.alter_column('agent_efficiency_log', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_nullable=False)
    op.alter_column('event_log', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_nullable=False)
    op.alter_column('file_conversion', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_nullable=False)
    op.alter_column('knowledge_entry', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_nullable=False)
    op.alter_column('menu', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_nullable=False)
    op.alter_column('message', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_nullable=False)
    op.alter_column('permission', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_nullable=False)
    op.alter_column('rating_record', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_nullable=False)
    op.alter_column('role', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_nullable=False)
    op.alter_column('satisfaction', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_nullable=False)
    op.add_column('session', sa.Column('last_message_at', sa.DateTime(), nullable=True))
    op.add_column('session', sa.Column('message_count', sa.Integer(), nullable=True))
    op.add_column('session', sa.Column('query_count', sa.Integer(), nullable=True))
    op.alter_column('session', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_nullable=False)
    op.alter_column('system_config', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_nullable=False)
    op.alter_column('tenant', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_nullable=False)
    op.alter_column('ticket', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_nullable=False)
    op.alter_column('ticket_comment', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_nullable=False)
    op.alter_column('translation', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_nullable=False)
    op.alter_column('user', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_nullable=False)
    op.alter_column('user_role', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_role', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('user', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('translation', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('ticket_comment', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('ticket', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('tenant', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('system_config', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('session', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='UUID',
               existing_nullable=False)
    op.drop_column('session', 'query_count')
    op.drop_column('session', 'message_count')
    op.drop_column('session', 'last_message_at')
    op.alter_column('satisfaction', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('role', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('rating_record', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('permission', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('message', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('menu', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('knowledge_entry', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('file_conversion', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('event_log', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('agent_efficiency_log', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('admin_user', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='UUID',
               existing_nullable=False)
    # ### end Alembic commands ###
